### ISSUE TITLE
Setting a different date format

### ISSUE THREAD

**Issue by Mulli** [wojtekmaj/react-date-picker#109]
**How do I change the dot in the date to slash ??** from dd.mm.yyyy to dd/mm/yyyy
I am using
```
<DatePicker 
  onChange={this.onChangeDate.bind(this)}
  value={this.state.date}
  locale="he-IL"
/>
```
Locale works nice! (almost... ) 2 issues:
a. I got the date as yyyy.mm.dd And forced css ltr direction to get: dd.mm.yyyy
b. Locale setting changed the dot to slash - is there an elegant way to get it back???
Thanks!

**Comment by wojtekmaj** [comment]
For issues on formatting, see #40 and #90.

Sadly, there's no way to customize the formatting, it is based your browser implementation of `Intl.DateTimeFormat`.

You can hack it a little with CSS though to get the dot back despite a locale that specifies slash:

```css
.react-date-picker__inputGroup__divider {
  font-size: 0;
}

.react-date-picker__inputGroup__divider:before {
  content: '.';
  font-size: 12px;
}
```

Mind you it's using class names in the newest version of React-Date-Picker. Dividers will have different class names in older versions (`.react-date-picker__button__input__divider`).
