### ISSUE TITLE
Calendar overflows on small devices

### ISSUE THREAD

**Issue by emibcn** [wojtekmaj/react-date-picker#124]
I Just wanted to share some code useful for me when calendar opens on small devices, as it easily overflows the screen. I've managed to fix it adding some CSS with a simple media query, making the calendar `position: fixed` and centered horizontally & vertically on small devices:
```css
/* Fix calendar position for small device (mobile first) */
.react-date-picker__calendar.react-date-picker__calendar--open {
    top: 50% !important;
    left: 50% !important;
    transform: translate(-50%,-50%) !important;
    position: fixed !important;
}

@media only screen and (min-width: 768px) {
    .react-date-picker__calendar.react-date-picker__calendar--open {
        top: 100% !important;
        left: 0 !important;
        transform: none !important;
        position: absolute !important;
    }   
}
```
