### ISSUE TITLE
Nostyle date-picker does not close on selection

### ISSUE THREAD

**Issue by valtism** [wojtekmaj/react-date-picker#262]
The normal date-picker closes on selection and on click outside. When using `react-date-picker/dist/entry.nostyle` the calendar no longer closes on selection, or click outside. 

The onCalendarClose function is fired, but no close happens.

Version:
`"react-date-picker": "^8.0.1"`

**Comment by valtism** [comment]
I found out that this is because the calendar is shown and hidden using CSS, not in react as I would expect. If using `nostyle`, make sure you include

```css
.react-date-picker__calendar--closed {
  display: none;
}
```

in your CSS
