### ISSUE TITLE
Huge horizontal scroll on dir="rtl"

### ISSUE THREAD

**Issue by pedrofsantoscom** [wojtekmaj/react-date-picker#304]
While having the page on `dir="rtl"`, the date picker component creates a huge horizontal scrollable area.
![image](https://user-images.githubusercontent.com/2325978/93015272-0844d780-f5b0-11ea-8234-1699819c37d8.png)
Open the popup on this demo: https://codesandbox.io/s/react-date-picker-forked-zkwwb

The issue only happens with react-date-picker.
I found out that unchecking `.MuiDialogContent-root` `overflow-y: auto` takes the huge horizontal scroll away. Any idea why this is happening or how to fix on react-date-picker side?
![image](https://user-images.githubusercontent.com/2325978/93015262-f2371700-f5af-11ea-9fb7-67d90c0c1a37.png)

**Comment by pedrofsantoscom** [comment]
Fixed with this css:
```css
.MuiDialogContent-root {
  overflow-y: auto;
  overflow-x: hidden !important;
}
```

**Comment by pedrofsantoscom** [comment]
> Fixed with this css:
> 
> ```css
> .MuiDialogContent-root {
>   overflow-y: auto;
>   overflow-x: hidden !important;
> }
> ```

Not a proper fix. On safari, sometimes when scrolling vertically, the browser scrolls all the way to the end of the horizontal scrollable area, making all the content inside the popup invisible to the user.
@wojtekmaj any idea what react-date-picker is doing to cause that huge h-scrollable area?

**Comment by pedrofsantoscom** [comment]
Fix for RTL:
```css
[dir='rtl'] .react-date-picker__inputGroup > [type='date'] {
      left: auto !important;
      right: -9999px !important;
  }
```

@wojtekmaj can you add this fix to the repo?
