### ISSUE TITLE
Disable date selection from input and restrict it only from the calendar.

### ISSUE THREAD

**Issue by Rahulgarg30591** [wojtekmaj/react-date-picker#78]
Hello @wojtekmaj, Thank you for creating and maintaining such a helpful package. Rest is there any option by which we can restrict a user for a Date change only from a calendar but not from the textbox.

If yes will be good if you may clarify it in the docs(props).

Thanks a lot again.
Rahul Garg

**Comment by wojtekmaj** [comment]
There's no such way programatically at the moment, but you can disable inputs by writing

```css
.react-date-picker__button__input__input {
  -moz-user-input: none;
  user-input: none;
}
```
